version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${ADBREW_CODEBASE_PATH}/src/app:/src/app
    ports:
      - "3000:3000"
    depends_on:
      - api
    environment:
      - NODE_ENV=development

  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${ADBREW_CODEBASE_PATH}/src:/src
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - ENV_TYPE=staging
      - MONGO_HOST=mongo
      - MONGO_PORT=27017

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
